// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnq26jY5UeaOCoxvBEYbrwFQyw57qEcLk',
    appId: '1:522262819217:web:212e6874a5b643b6e82a30',
    messagingSenderId: '522262819217',
    projectId: 'fir-series-38d1d',
    authDomain: 'fir-series-38d1d.firebaseapp.com',
    databaseURL: 'https://fir-series-38d1d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-series-38d1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePsYHUGE3yOjbvaAXFn5c9g5ExSd2MgQ',
    appId: '1:522262819217:android:b2c728d0dd231f1ae82a30',
    messagingSenderId: '522262819217',
    projectId: 'fir-series-38d1d',
    databaseURL: 'https://fir-series-38d1d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-series-38d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iOWfxeUDXjs4YDfS21Wa9JJ5ORGfpIE',
    appId: '1:522262819217:ios:cbade5c89a56006de82a30',
    messagingSenderId: '522262819217',
    projectId: 'fir-series-38d1d',
    databaseURL: 'https://fir-series-38d1d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-series-38d1d.appspot.com',
    androidClientId: '522262819217-a9tlmr793djdje3l91p83qh5a4dnoibh.apps.googleusercontent.com',
    iosClientId: '522262819217-7j4idhdqcjfc1nneo9rus4m5d5i5qp7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCall',
  );

}